# Build from local source code using Maven and run with Tomcat
FROM maven:3.9.12-eclipse-temurin-17 AS builder
COPY . /usr/src/app/
WORKDIR /usr/src/app/
RUN mvn -B clean package

FROM tomcat:9-jdk17-openjdk-slim
COPY --from=builder /usr/src/app/target/mongodb-slow-operations-profiler.war /tmp
WORKDIR /usr/local/tomcat/webapps/mongodb-slow-operations-profiler/
RUN jar -xfv /tmp/mongodb-slow-operations-profiler.war
RUN chown -R nobody:nogroup /usr/local/tomcat/webapps/
USER nobody:nogroup